version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing Maven..."
      - apt-get update && apt-get install -y maven
      - mvn -v

  build:
    commands:
      - echo "Running Maven clean verify for JaCoCo and tests..."
      - mvn clean verify

  post_build:
    commands:
      - echo "Build complete. JaCoCo report should be in target/site/jacoco/index.html"
      - echo "Uploading JaCoCo report to S3..."
      - aws s3 cp target/site/jacoco/index.html s3://codepipeline-us-east-1-7f42f5116fdb-4981-b6cc-d62285290805/SimpleCarRentalApp-P/reports/jacoco/index.html --sse aws:kms
      - echo "Sending SNS notification..."
      - |
        REPORT_URL=$(aws s3 presign s3://codepipeline-us-east-1-7f42f5116fdb-4981-b6cc-d62285290805/SimpleCarRentalApp-P/reports/jacoco/index.html --expires-in 3600)
        MESSAGE="✅ CodeBuild succeeded.\n\n📊 View JaCoCo report: $REPORT_URL"

        aws sns publish --topic-arn arn:aws:sns:us-east-1:637061300326:SimpleCarRentalApp-CodeBuild-Notifications --subject "✅ CodeBuild Success - JaCoCo Report Available" --message "$MESSAGE"

artifacts:
  files:
    - target/*.war
    - target/site/jacoco/**/*
  discard-paths: no
