version: 0.2

env:
  variables:
    REPORT_BUCKET: simplecarrentalapp-devsecops-reports
    REPORT_PATH: SimpleCarRentalApp-P/reports
    SNS_TOPIC_ARN: arn:aws:sns:us-east-1:637061300326:SimpleCarRentalApp-CodeBuild-Notifications

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing dependencies...
      - apt-get update
      - apt-get install -y unzip wget
      - wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
      - unzip dependency-check-8.4.0-release.zip -d /opt

  pre_build:
    commands:
      - echo Running OWASP Dependency-Check...
      - mkdir -p dependency-check-report
      - /opt/dependency-check/bin/dependency-check.sh --project "SimpleCarRentalApp" --scan . --format HTML --out dependency-check-report

  build:
    commands:
      - echo Running Maven Build with JaCoCo...
      - mvn clean verify

  post_build:
    commands:
      - echo "Uploading JaCoCo and Dependency-Check reports to S3 with encryption..."
      - aws s3 cp target/site/jacoco/ s3://$REPORT_BUCKET/$REPORT_PATH/jacoco/ --recursive --sse AES256
      - aws s3 cp dependency-check-report/ s3://$REPORT_BUCKET/$REPORT_PATH/dependency-check/ --recursive --sse AES256

      - echo "Generating presigned URLs for JaCoCo and SCA reports..."
      - export JACOCO_URL=$(aws s3 presign s3://$REPORT_BUCKET/$REPORT_PATH/jacoco/index.html --expires-in 86400)
      - export SCA_URL=$(aws s3 presign s3://$REPORT_BUCKET/$REPORT_PATH/dependency-check/dependency-check-report.html --expires-in 86400)

      - echo "Sending SNS notification with report links..."
      - |
        export MESSAGE="✅ CodeBuild succeeded for SimpleCarRentalApp.

📊 View JaCoCo Report: $JACOCO_URL

🛡️ View Dependency-Check (SCA) Report: $SCA_URL"
        aws sns publish \
          --topic-arn "$SNS_TOPIC_ARN" \
          --subject "✅ CodeBuild Success: SimpleCarRentalApp" \
          --message "$MESSAGE"

reports:
  jacoco:
    files:
      - target/site/jacoco/index.html
    base-directory: target/site/jacoco
    discard-paths: yes

artifacts:
  files:
    - target/*.war
    - target/site/jacoco/**/*
    - dependency-check-report/**/*
  discard-paths: no
