version: 0.2

env:
  variables:
    REPORT_BUCKET: simplecarrentalapp-devsecops-reports
    REPORT_PATH: SimpleCarRentalApp-P/reports
    SNS_TOPIC_ARN: arn:aws:sns:us-east-1:637061300326:SimpleCarRentalApp-CodeBuild-Notifications

phases:
  install:
    commands:
      - echo Installing Docker...
      - yum update -y
      - yum install -y docker
      - service docker start

  pre_build:
    commands:
      - echo Running ZAP Baseline Scan...
      - chmod +x zap-dast.sh
      - ./zap-dast.sh

  post_build:
    commands:
      - echo Uploading ZAP report to S3...
      - aws s3 cp zap-report/zap-report.html s3://$REPORT_BUCKET/$REPORT_PATH/zap-report.html --sse AES256
      - export ZAP_URL=$(aws s3 presign s3://$REPORT_BUCKET/$REPORT_PATH/zap-report.html --expires-in 86400)

      - echo Sending SNS Notification...
      - |
        MESSAGE="⚠️ *DAST (ZAP) Report Ready* ⚠️\n\n🌐 Target: SimpleCarRentalApp-Staging\n\n📄 Report: $ZAP_URL"
        aws sns publish \
          --topic-arn "$SNS_TOPIC_ARN" \
          --subject "⚠️ DAST Scan Completed (ZAP)" \
          --message "$MESSAGE"
