version: 0.2

env:
  variables:
    REPORT_BUCKET: simplecarrentalapp-devsecops-reports
    REPORT_PATH: SimpleCarRentalApp-P/reports
    SNS_TOPIC_ARN: arn:aws:sns:us-east-1:637061300326:SimpleCarRentalApp-CodeBuild-Notifications

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies...
      - apt-get update
      - apt-get install -y unzip wget zip
      - wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
      - unzip dependency-check-8.4.0-release.zip -d /opt

  pre_build:
    commands:
      - echo Running OWASP Dependency-Check...
      - export NVD_API_KEY=$(aws ssm get-parameter --name /devsecops/nvd/apikey --with-decryption --query "Parameter.Value" --output text)
      - >
        /opt/dependency-check/bin/dependency-check.sh
        --project "SimpleCarRentalApp"
        --scan .
        --format HTML
        --out $REPORT_PATH/dependency-check
        --disableCentral
        --nvdApiKey $NVD_API_KEY \
        --failOnCVSS 11 || echo "Dependency-Check completed with non-zero exit, continuing..."

  build:
    commands:
      - echo Running Maven Build with JaCoCo...
      - mvn clean verify

      - echo Fetching SonarCloud token from AWS SSM Parameter Store...
      - export SONAR_TOKEN=$(aws ssm get-parameter --name /devsecops/sonar/token --with-decryption --query "Parameter.Value" --output text)

      - echo Running SonarCloud analysis...
      - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=SimpleCarRentalApp \
          -Dsonar.organization=praveenmummella \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml || echo "SonarCloud analysis failed, continuing..."

  post_build:
    commands:
      - echo "Uploading JaCoCo and Dependency-Check reports to S3 with encryption..."
      - aws s3 cp target/site/jacoco/ s3://$REPORT_BUCKET/$REPORT_PATH/jacoco/ --recursive --sse AES256
      - aws s3 cp $REPORT_PATH/dependency-check/ s3://$REPORT_BUCKET/$REPORT_PATH/dependency-check/ --recursive --sse AES256

      - echo "Zipping JaCoCo report for easier navigation..."
      - zip -r jacoco-report.zip target/site/jacoco/

      - echo "Uploading zipped report to S3..."
      - aws s3 cp jacoco-report.zip s3://$REPORT_BUCKET/$REPORT_PATH/jacoco-report.zip --sse AES256

      - echo "Generating presigned URL for zipped report..."
      - export JACOCO_ZIP_URL=$(aws s3 presign s3://$REPORT_BUCKET/$REPORT_PATH/jacoco-report.zip --region us-east-1 --expires-in 86400)

      - echo "Generating presigned URL for Dependency-Check (SCA) report..."
      - export SCA_URL=$(aws s3 presign s3://$REPORT_BUCKET/$REPORT_PATH/dependency-check/dependency-check-report.html --expires-in 86400)

      - echo "Sending combined SNS notification..."
      - >
        export MESSAGE="✅ CodeBuild succeeded for SimpleCarRentalApp.\n\n📦 Download full JaCoCo report (ZIP): $JACOCO_ZIP_URL\n\n🔍 Dependency-Check Report (SCA): $SCA_URL\n\n🔐 SonarCloud Dashboard: https://sonarcloud.io/project/overview?id=SimpleCarRentalApp" && 
        aws sns publish \
          --topic-arn "$SNS_TOPIC_ARN" \
          --subject "✅ CodeBuild Success: All Reports Ready" \
          --message "$MESSAGE"

reports:
  jacoco:
    files:
      - target/site/jacoco/index.html
    base-directory: target/site/jacoco
    discard-paths: yes

artifacts:
  files:
    - target/*.war
    - target/site/jacoco/**/*
  discard-paths: no
